# Stores sample test data found from here: https://api.globe.gov/search/swagger-ui.html#/v-1-controller/findUsingGET

# 2 Landcover Entries
sample_lc_json = """
    {
    "count": 1710,
    "message": "success",
    "results": [
        {
        "protocol": "land_covers",
        "measuredDate": "2010-10-05",
        "createDate": "2021-03-29T10:43:01",
        "updateDate": "2021-03-29T10:43:01",
        "publishDate": "2021-03-29T10:49:19",
        "organizationId": 326812,
        "organizationName": "Escuela de Educacion  Media N 8",
        "siteId": 132,
        "siteName": "VICENTE LOPEZ:LCS-01",
        "countryName": "Argentina",
        "countryCode": "ARG",
        "latitude": -34.552,
        "longitude": -58.483,
        "elevation": 42,
        "pid": 187086150,
        "data": {
            "landcoversDownwardPhotoUrl": null,
            "landcoversEastExtraData": null,
            "landcoversEastPhotoUrl": null,
            "landcoversMucCode": "M91",
            "landcoversUpwardPhotoUrl": null,
            "landcoversEastCaption": null,
            "landcoversWestClassifications": null,
            "landcoversNorthCaption": null,
            "landcoversNorthExtraData": null,
            "landcoversDataSource": "GLOBE Data Entry Site Definition",
            "landcoversDryGround": null,
            "landcoversSouthClassifications": null,
            "landcoversWestCaption": null,
            "landcoversNorthPhotoUrl": null,
            "landcoversUpwardCaption": null,
            "landcoversDownwardExtraData": null,
            "landcoversEastClassifications": null,
            "landcoversMucDetails": null,
            "landcoversMeasuredAt": "2010-10-05T00:00:00",
            "landcoversDownwardCaption": null,
            "landcoversSouthPhotoUrl": null,
            "landcoversMuddy": null,
            "landcoversWestPhotoUrl": null,
            "landcoversStandingWater": null,
            "landcoversLeavesOnTrees": null,
            "landcoversUserid": null,
            "landcoversSouthExtraData": null,
            "landcoversSouthCaption": null,
            "landcoversRainingSnowing": null,
            "landcoversUpwardExtraData": null,
            "landcoversWestExtraData": null,
            "landcoversLandCoverId": 12736,
            "landcoversMucDescription": "Urban, Residential",
            "landcoversSnowIce": null,
            "landcoversNorthClassifications": null,
            "landcoversFieldNotes": "Urban, Residential :: please replace with Land Cover Site Comments"
        }
        },
        {
        "protocol": "land_covers",
        "measuredDate": "2012-05-11",
        "createDate": "2021-03-29T10:43:12",
        "updateDate": "2021-03-29T10:43:12",
        "publishDate": "2021-03-29T10:49:19",
        "organizationId": 326053,
        "organizationName": "Domingo Faustino Sarmiento",
        "siteId": 133,
        "siteName": "Mision Baja:LCS-01",
        "countryName": "Argentina",
        "countryCode": "ARG",
        "latitude": -54.4892,
        "longitude": -68.18545,
        "elevation": -12.2,
        "pid": 187086632,
        "data": {
            "landcoversDownwardPhotoUrl": null,
            "landcoversEastExtraData": "null",
            "landcoversEastPhotoUrl": "https://data.globe.gov/system/photos/2012/11/03/4070/original.JPG",
            "landcoversMucCode": "M94",
            "landcoversUpwardPhotoUrl": null,
            "landcoversEastCaption": "",
            "landcoversWestClassifications": null,
            "landcoversNorthCaption": "",
            "landcoversNorthExtraData": "null",
            "landcoversDataSource": "GLOBE Data Entry Site Definition",
            "landcoversDryGround": null,
            "landcoversSouthClassifications": null,
            "landcoversWestCaption": "",
            "landcoversNorthPhotoUrl": "https://data.globe.gov/system/photos/2012/11/03/4073/original.JPG",
            "landcoversUpwardCaption": null,
            "landcoversDownwardExtraData": null,
            "landcoversEastClassifications": null,
            "landcoversMucDetails": null,
            "landcoversMeasuredAt": "2012-05-11T00:00:00",
            "landcoversDownwardCaption": null,
            "landcoversSouthPhotoUrl": "https://data.globe.gov/system/photos/2012/11/03/4075/original.JPG",
            "landcoversMuddy": null,
            "landcoversWestPhotoUrl": "https://data.globe.gov/system/photos/2012/11/03/4076/original.JPG",
            "landcoversStandingWater": null,
            "landcoversLeavesOnTrees": null,
            "landcoversUserid": null,
            "landcoversSouthExtraData": "null",
            "landcoversSouthCaption": "",
            "landcoversRainingSnowing": null,
            "landcoversUpwardExtraData": null,
            "landcoversWestExtraData": "null",
            "landcoversLandCoverId": 12737,
            "landcoversMucDescription": "Urban, Other",
            "landcoversSnowIce": null,
            "landcoversNorthClassifications": null,
            "landcoversFieldNotes": "Urban, Other :: SCRC data (please do not delete me!)   SCRC data (please do not delete me!)   SCRC data (please do not delete me!) el situo de estudio esta medianamente poblada, la superficie es de pasto muy cerca de la Bahia y con calles de tierra."
        }
        }
    ]
    }
    """

# 2 Mosquito Habitat Mapper entries
sample_mhm_json = """
{
  "count": 1377,
  "message": "success",
  "results": [
    {
      "protocol": "mosquito_habitat_mapper",
      "measuredDate": "2017-05-29",
      "createDate": "2021-03-29T10:51:23",
      "updateDate": "2021-03-29T10:51:23",
      "publishDate": "2021-03-29T13:30:46",
      "organizationId": 12993805,
      "organizationName": "Canyon Weather",
      "siteId": 35802,
      "siteName": "11SMT309762",
      "countryName": "United States",
      "countryCode": "USA",
      "latitude": 34.124374,
      "longitude": -117.749344,
      "elevation": 485.3,
      "pid": 187103023,
      "data": {
        "mosquitohabitatmapperBreedingGroundEliminated": false,
        "mosquitohabitatmapperExtraData": null,
        "mosquitohabitatmapperAbdomenCloseupPhotoUrls": null,
        "mosquitohabitatmapperMeasuredAt": "2017-05-29T19:08:00",
        "mosquitohabitatmapperMeasurementElevation": 485.3,
        "mosquitohabitatmapperUserid": 11114,
        "mosquitohabitatmapperLarvaeCount": null,
        "mosquitohabitatmapperMosquitoEggs": null,
        "mosquitohabitatmapperMosquitoEggCount": null,
        "mosquitohabitatmapperGenus": null,
        "mosquitohabitatmapperWaterSource": "fountain or bird bath",
        "mosquitohabitatmapperMosquitoAdults": null,
        "mosquitohabitatmapperSpecies": null,
        "mosquitohabitatmapperComments": null,
        "mosquitohabitatmapperMosquitoPupae": null,
        "mosquitohabitatmapperWaterSourcePhotoUrls": "https://data.globe.gov/system/photos/2017/05/29/166949/original.jpg",
        "mosquitohabitatmapperDataSource": "GLOBE Observer App",
        "mosquitohabitatmapperLarvaFullBodyPhotoUrls": null,
        "mosquitohabitatmapperMeasurementLatitude": 34.124374,
        "mosquitohabitatmapperLastIdentifyStage": null,
        "mosquitohabitatmapperWaterSourceType": "container: artificial",
        "mosquitohabitatmapperMosquitoHabitatMapperId": 4,
        "mosquitohabitatmapperMeasurementLongitude": -117.749344
      }
    },
    {
      "protocol": "mosquito_habitat_mapper",
      "measuredDate": "2017-05-29",
      "createDate": "2021-03-29T10:51:23",
      "updateDate": "2021-03-29T10:51:23",
      "publishDate": "2021-03-29T13:30:46",
      "organizationId": 12993805,
      "organizationName": "Canyon Weather",
      "siteId": 35822,
      "siteName": "11SMT309761",
      "countryName": "United States",
      "countryCode": "USA",
      "latitude": 34.123473,
      "longitude": -117.749336,
      "elevation": 467.6,
      "pid": 187103024,
      "data": {
        "mosquitohabitatmapperBreedingGroundEliminated": true,
        "mosquitohabitatmapperExtraData": null,
        "mosquitohabitatmapperAbdomenCloseupPhotoUrls": null,
        "mosquitohabitatmapperMeasuredAt": "2017-05-29T19:12:00",
        "mosquitohabitatmapperMeasurementElevation": 467.6,
        "mosquitohabitatmapperUserid": 11114,
        "mosquitohabitatmapperLarvaeCount": "0",
        "mosquitohabitatmapperMosquitoEggs": false,
        "mosquitohabitatmapperMosquitoEggCount": null,
        "mosquitohabitatmapperGenus": null,
        "mosquitohabitatmapperWaterSource": "cement, metal or plastic tank",
        "mosquitohabitatmapperMosquitoAdults": false,
        "mosquitohabitatmapperSpecies": null,
        "mosquitohabitatmapperComments": null,
        "mosquitohabitatmapperMosquitoPupae": false,
        "mosquitohabitatmapperWaterSourcePhotoUrls": "https://data.globe.gov/system/photos/2017/05/29/166951/original.jpg",
        "mosquitohabitatmapperDataSource": "GLOBE Observer App",
        "mosquitohabitatmapperLarvaFullBodyPhotoUrls": null,
        "mosquitohabitatmapperMeasurementLatitude": 34.123473,
        "mosquitohabitatmapperLastIdentifyStage": "identify",
        "mosquitohabitatmapperWaterSourceType": "container: artificial",
        "mosquitohabitatmapperMosquitoHabitatMapperId": 6,
        "mosquitohabitatmapperMeasurementLongitude": -117.749336
      }
    }
  ]
}
"""

# Output json whenever the GLOBE API is down
globe_down_json = """{
    "type": "FeatureCollection",
    "name": "GLOBE-data",
    "features": [],
    "message": "failure: Connection refused"
    }"""
