name: Lint and Format

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Check formatting
      run: |
        pip install black
        black --check --diff ./
    - name: Check import sorting
      run: |
        pip install isort
        isort ./ --profile black --check-only
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Run Flake8 Linter
      run: |
        pip install flake8
        flake8